config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :categories do
    resources :my_transactions
  end
  # resources :users

  root "splash_screen#show"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :SplashScreen
    return unless user.present?

    can :manage, Category, user_id: user.id
    can :manage, MyTransaction, user_id: user.id

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  include ImageUploader::Attachment(:image)

  belongs_to :user

  has_many :category_my_transactions, dependent: :destroy
  has_many :my_transactions, through: :category_my_transactions

  validates :name, presence: true, length: { in: 2..30 }
end

app/models/category_my_transaction.rb
class CategoryMyTransaction < ApplicationRecord
  belongs_to :category
  belongs_to :my_transaction
end

app/models/my_transaction.rb
class MyTransaction < ApplicationRecord
  belongs_to :user

  has_many :category_my_transactions, dependent: :destroy
  has_many :categories, through: :category_my_transactions

  validates :name, presence: true, length: { in: 3..30 }
  validates :amount, presence: true, numericality: { only_float: true, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable # , :confirmable

  has_many :my_transactions
  has_many :categories

  validates :name, presence: true, length: { in: 5..50 }

  def admin?
    role == 'admin'
  end

  def total_expenditure
    my_transactions.sum(:amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_up_path?
    new_user_session_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource except: %i[create]
  before_action :set_category, only: %i[show edit update destroy]
  before_action :set_user

  def index
    @categories = @user.categories.all
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    @category.user = @user

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :user_id, :image)
  end
end

app/controllers/my_transactions_controller.rb
class MyTransactionsController < ApplicationController
  load_and_authorize_resource

  before_action :set_my_transaction, only: %i[show edit update destroy]

  before_action :set_user
  before_action :set_category
  before_action :set_category_my_transaction
  before_action :set_categories

  def index
    @my_transactions = @category.my_transactions.order(created_at: :desc)
    @category_my_transactions = @category.category_my_transactions
  end

  def show; end

  def new
    @my_transaction = MyTransaction.new
  end

  def edit; end

  def create
    @my_transaction = MyTransaction.new(my_transaction_params)
    @my_transaction.user = @user

    respond_to do |format|
      if @my_transaction.save
        CategoryMyTransaction.create!(category_id: @category.id, my_transaction_id: @my_transaction.id)
        format.html do
          redirect_to category_my_transactions_url(category_id: @category.id),
                      notice: 'My transaction was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @my_transaction.update(my_transaction_params)
        format.html do
          redirect_to category_my_transactions_url(category_id: @category.id, id: @my_transaction.id),
                      notice: 'My transaction was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category_my_transactions = CategoryMyTransaction.where(category_id: @category.id,
                                                            my_transaction_id: @my_transaction.id)

    @category_my_transactions.each(&:destroy)

    respond_to do |format|
      format.html do
        redirect_to category_my_transactions_url(category_id: @category.id),
                    notice: 'My transaction was successfully destroyed.'
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_my_transaction
    @my_transaction = MyTransaction.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_categories
    @categories = @user.categories
  end

  def set_category_my_transaction
    @category_my_transaction = CategoryMyTransaction.where(category_id: params[:category_id]).order(created_at: :desc)
  end

  # Only allow a list of trusted parameters through.
  def my_transaction_params
    params.require(:my_transaction).permit(:name, :amount, :category_ids, :user_id)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  load_and_authorize_resource except: %i[show]
  skip_before_action :authenticate_user!
  def show
    redirect_to categories_path if user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_user_session_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/my_transactions_helper.rb
module MyTransactionsHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="category-grid">

  <div class="categ-icon-and-name">
    <p>
      <%= image_tag category.image_url, class:"categ-icon" if category.image %>
    </p>

    <p class="categ-name-text">
      <%= category.name %>
    </p>
  </div>

  <h3 class="categ-amount"> <%= category.my_transactions.sum(:amount) %> </h3>


</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, url: categories_path, class:"form-add-categ") do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, autofocus: true, placeholder:"Category name"%>
  </div>

  <div class="field field-image">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="add-trans">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="categ-index">
  <div class="header header-categ-trans">
  <%= button_to "Logout",
  destroy_user_session_path, method: :delete, class: "logout-btn" %>

    <h1>Categories</h1>
    <%= image_tag('search.svg', class: "icon-search") %>
  </div>

  <div class="total-expenditure">
  <h4> My total expenditure </h4>
  <p> <%= current_user.total_expenditure %> </p>
  </div>



 <div class="categ-body">
  <div id="categories">
  <% @categories.each do |category| %>
    <a href=<%= category_my_transactions_path(category_id: category.id) %>>

    <%= render category %>

    </a>

  <% end %>
  </div>
  <p class="new-categ">
    <%= link_to "Add new category",  new_category_path %>
  </p>
 </div>
</div>

app/views/categories/new.html.erb
<div class="category-wrapper categ-add-wrapper">
<div class="header header-categ-trans">
  <%= link_to categories_path do %>
    <%= image_tag('back.svg', class: "icon-back") %>
  <% end %>
  <h1>Add new category</h1>
</div>

  <%= render "form", category: @category %>

  <br>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="header header-categ-trans header-trans-details">
    <%= link_to categories_path do %>
      <%= image_tag('back.svg', class: "icon-back") %>
    <% end %>
    <h1 class="details-title"> Details </h1>
  </div>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="/app/assets/stylesheets/proxy-nov/fonts.min.css" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
<!---
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      --->

      <%= yield %>
    </div>
  </body>
</html>

app/views/my_transactions/_form.html.erb
<%= form_with(model: my_transaction, url: category_my_transaction_path(category_id: @category.id,
id: @my_transaction.id)) do |form| %>
  <% if my_transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(my_transaction.errors.count, "error") %> prohibited this my_transaction from being saved:</h2>

      <ul>
        <% my_transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>
  <!---
  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div> --->

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/my_transactions/_form_new.html.erb
<%= form_with(model: my_transaction,
url: category_my_transactions_path(category_id: @category.id),
class:"form-add-trans") do |form| %>
  <% if my_transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(my_transaction.errors.count, "error") %> prohibited this my_transaction from being saved:</h2>

      <ul>
        <% my_transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, autocomplete: true, autofocus: true, placeholder: "Transaction name" %>
  </div>

  <div class="field">
    <%= form.text_field :amount, autocomplete: true, autofocus: true, placeholder: "Amount" %>
  </div>
  <!---
  <div>
    <%= form.text_field :user_id %>
  </div> --->

  <!--- <%  @categories.each do |item|%>
    <%p params[:category_id].to_i%>
      <% if item.id == params[:category_id].to_i%>
        <%= check_box_tag "params[:my_transaction][:category_ids][]", item.id, true%>
      <%else%>
        <%= check_box_tag "params[:my_transaction][:category_ids][]", item.id%>
      <%end%>
      <%= item.name%><br>
    <%end%>   --->

  <div class="add-trans">
    <%= form.submit %>
  </div>
<% end %>

app/views/my_transactions/_my_transaction.html.erb
<div id="<%= dom_id my_transaction %>" class="details-body-container">

  <div class="header header-categ-trans header-trans-details">
    <%= link_to category_my_transactions_path(category_id: @category.id) do %>
      <%= image_tag('back.svg', class: "icon-back") %>
    <% end %>
    <h1 class="details-title"> Details </h1>
  </div>

  <div class="details-grid">
    <div class="details-header-body">
      <div class="icon-name-details">
        <div>
          <% if @category.image %>
          <%= image_tag @category.image_url, class:"categ-icon" %>
          <% else %>
            <%= image_tag('transport.png') %>
          <% end %>
        </div>
        <p class="trans-name-text"><%= @my_transaction.name %></p>
      </div>
      <p class="details-body">
        <%= Faker::Lorem.paragraph_by_chars(number: 100, supplemental: false) %>
      </p>
    </div>

    <div class="trans-name-date">
      <p> Transaction took place </p>

      <% if Time.now - @my_transaction.created_at <= 1.minute %>
        <h4 class="trans-date-text"><%= time_ago_in_words(@my_transaction.created_at, include_seconds: true) %> ago</h4>
      <% elsif Time.now - @my_transaction.created_at <= 24.hours %>
        <h4 class="trans-date-text"><%= time_ago_in_words(@my_transaction.created_at) %> ago</h4>
      <% else %>
        <h4 class="trans-date-text"><%= @my_transaction.created_at.strftime('%b %d, %Y') %></h4>

      <% end %>
    </div>

    <div class="trans-amount">
      <h3>Total payment $<%= @my_transaction.amount %></h3>
    </div>

  </div>



</div>

app/views/my_transactions/edit.html.erb
<h1>Editing my transaction</h1>

<%= render "form", my_transaction: @my_transaction %>

<br>

<div>
  <%= link_to "Show this my transaction", category_my_transaction_path(category_id: @category.id,
  id: @my_transaction.id) %> |
  <%= link_to "Back to my transactions", category_my_transaction_path(category_id: @category.id,
  id: @my_transaction.id) %>
</div>

app/views/my_transactions/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="categ-index">
  <div class="header-wider">

    <div class="header header-categ-trans">
      <%= link_to categories_path do %>
        <%= image_tag('back.svg', class: "icon-back") %>
      <% end %>
      <h1>My transactions</h1>
      <%= image_tag('search.svg', class: "icon-search") %>
    </div>
    <h2 class="most-recent-text"> Most recent </h2>
  </div>

  <div class="total-categ-trans">
    <div class="total-categ-trans-icon-name">
      <%= image_tag @category.image_url, class:"categ-icon" if @category.image %>
      <h2 class="trans-name-text"> Total <%= @category.name %> transactions </h2>
    </div>
    <h3 class="trans-amount"> $<%= @category.my_transactions.sum(:amount) %> </h3>
  </div>

  <div class="trans-body">
    <% if @my_transactions.any? %>
      <div id="my_transactions">

        <% @category_my_transactions.includes(:my_transaction).each_with_index do |category_my_transaction, index| %>
          <a href=<%= category_my_transaction_path(category_id: @category.id,
          id: category_my_transaction.my_transaction_id) %> class="trans-grid-link">
            <div class="trans-grid">
              <div class="icon-trans-name-date">
                <div>
                  <% if @category.image %>
                  <%= image_tag @category.image_url, class:"categ-icon" %>
                  <% else %>
                    <%= image_tag('transport.png') %>
                  <% end %>
                </div>

                <div class="trans-name-date">
                  <p class="trans-name-text"><%= category_my_transaction.my_transaction.name %></p>
                  <% if Time.now - category_my_transaction.created_at <= 1.minute %>
                    <h4 class="trans-date-text"><%= time_ago_in_words(category_my_transaction.created_at, include_seconds: true) %> ago</h4>
                  <% elsif Time.now - category_my_transaction.created_at <= 24.hours %>
                    <h4 class="trans-date-text"><%= time_ago_in_words(category_my_transaction.created_at) %> ago</h4>
                  <% else %>
                    <h4 class="trans-date-text"><%= category_my_transaction.created_at.strftime('%b %d, %Y') %></h4>

                  <% end %>
                </div>
              </div>

              <div class="trans-amount">
                <h3>$<%= category_my_transaction.my_transaction.amount %></h3>
              </div>

            </div>

          </a>

        <% end %>
      </div>
    <% else %>
      <p class="notice">No transaction  for the <%= @category.name %> category</p>
    <% end %>

  </div> <!---- End of trans-body div tag ---->

  <div class="new-trans show-categ-links">
  <p>
    <%= link_to "Add transaction", new_category_my_transaction_path(category_id: @category.id) %>
  </p>
    <%= button_to "Destroy this category", @category, method: :delete, class: "btn-dest-categ" %>
  </div>
</div>

app/views/my_transactions/new.html.erb
<div class="header header-categ-trans">
  <%= link_to category_my_transactions_path(category_id: @category.id) do %>
    <%= image_tag('back.svg', class: "icon-back") %>
  <% end %>
  <h1>Add transaction </h1>
</div>

<%= render "form_new", my_transaction: @my_transaction %>

app/views/my_transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="details-wrapper">

<%= render @my_transaction %>

<div class="details-links">
  <%= link_to "Edit this transaction", edit_category_my_transaction_path(category_id: @category.id,
  id: @my_transaction.id), class: "details-edit-link" %>


  <%= button_to "Remove this transaction", category_my_transaction_path(category_id: @category.id,
  id: @my_transaction.id),
   method: :delete, class:"details-delete-btn" %>
</div>

app/views/splash_screen/show.html.erb
<div class="splash-screen-container">
  <h1> Awesome Budget Management </h1>
  <div class="accounts-container">
    <%= link_to "LOG IN", new_user_session_path, class: "account login-link"%>
    <%= link_to "SIGN UP", new_user_registration_path , class: "account signup-link" %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>